// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: carman.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Transmission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rotations     int32                  `protobuf:"varint,1,opt,name=rotations,proto3" json:"rotations,omitempty"`
	EngagedGear   int32                  `protobuf:"varint,2,opt,name=engaged_gear,json=engagedGear,proto3" json:"engaged_gear,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transmission) Reset() {
	*x = Transmission{}
	mi := &file_carman_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transmission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transmission) ProtoMessage() {}

func (x *Transmission) ProtoReflect() protoreflect.Message {
	mi := &file_carman_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transmission.ProtoReflect.Descriptor instead.
func (*Transmission) Descriptor() ([]byte, []int) {
	return file_carman_proto_rawDescGZIP(), []int{0}
}

func (x *Transmission) GetRotations() int32 {
	if x != nil {
		return x.Rotations
	}
	return 0
}

func (x *Transmission) GetEngagedGear() int32 {
	if x != nil {
		return x.EngagedGear
	}
	return 0
}

type Audi struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plate         string                 `protobuf:"bytes,1,opt,name=plate,proto3" json:"plate,omitempty"`
	Transmission  *Transmission          `protobuf:"bytes,2,opt,name=transmission,proto3" json:"transmission,omitempty"`
	SpeedInKmH    int32                  `protobuf:"varint,3,opt,name=speed_in_km_h,json=speedInKmH,proto3" json:"speed_in_km_h,omitempty"`
	EngineStarted bool                   `protobuf:"varint,4,opt,name=engine_started,json=engineStarted,proto3" json:"engine_started,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Audi) Reset() {
	*x = Audi{}
	mi := &file_carman_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Audi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Audi) ProtoMessage() {}

func (x *Audi) ProtoReflect() protoreflect.Message {
	mi := &file_carman_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Audi.ProtoReflect.Descriptor instead.
func (*Audi) Descriptor() ([]byte, []int) {
	return file_carman_proto_rawDescGZIP(), []int{1}
}

func (x *Audi) GetPlate() string {
	if x != nil {
		return x.Plate
	}
	return ""
}

func (x *Audi) GetTransmission() *Transmission {
	if x != nil {
		return x.Transmission
	}
	return nil
}

func (x *Audi) GetSpeedInKmH() int32 {
	if x != nil {
		return x.SpeedInKmH
	}
	return 0
}

func (x *Audi) GetEngineStarted() bool {
	if x != nil {
		return x.EngineStarted
	}
	return false
}

type CarList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// For simplicity in this example, we return a list of Audis.
	Cars          []*Audi `protobuf:"bytes,1,rep,name=cars,proto3" json:"cars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CarList) Reset() {
	*x = CarList{}
	mi := &file_carman_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarList) ProtoMessage() {}

func (x *CarList) ProtoReflect() protoreflect.Message {
	mi := &file_carman_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarList.ProtoReflect.Descriptor instead.
func (*CarList) Descriptor() ([]byte, []int) {
	return file_carman_proto_rawDescGZIP(), []int{2}
}

func (x *CarList) GetCars() []*Audi {
	if x != nil {
		return x.Cars
	}
	return nil
}

type Void struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Void) Reset() {
	*x = Void{}
	mi := &file_carman_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Void) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Void) ProtoMessage() {}

func (x *Void) ProtoReflect() protoreflect.Message {
	mi := &file_carman_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Void.ProtoReflect.Descriptor instead.
func (*Void) Descriptor() ([]byte, []int) {
	return file_carman_proto_rawDescGZIP(), []int{3}
}

var File_carman_proto protoreflect.FileDescriptor

const file_carman_proto_rawDesc = "" +
	"\n" +
	"\fcarman.proto\x12\x05proto\"O\n" +
	"\fTransmission\x12\x1c\n" +
	"\trotations\x18\x01 \x01(\x05R\trotations\x12!\n" +
	"\fengaged_gear\x18\x02 \x01(\x05R\vengagedGear\"\x9f\x01\n" +
	"\x04Audi\x12\x14\n" +
	"\x05plate\x18\x01 \x01(\tR\x05plate\x127\n" +
	"\ftransmission\x18\x02 \x01(\v2\x13.proto.TransmissionR\ftransmission\x12!\n" +
	"\rspeed_in_km_h\x18\x03 \x01(\x05R\n" +
	"speedInKmH\x12%\n" +
	"\x0eengine_started\x18\x04 \x01(\bR\rengineStarted\"*\n" +
	"\aCarList\x12\x1f\n" +
	"\x04cars\x18\x01 \x03(\v2\v.proto.AudiR\x04cars\"\x06\n" +
	"\x04Void2]\n" +
	"\n" +
	"CarService\x12%\n" +
	"\aAddAudi\x12\v.proto.Audi\x1a\v.proto.Void\"\x00\x12(\n" +
	"\aGetCars\x12\v.proto.Void\x1a\x0e.proto.CarList\"\x00B8Z6golang.source-fellows.com/training/carman/v6/api/protob\x06proto3"

var (
	file_carman_proto_rawDescOnce sync.Once
	file_carman_proto_rawDescData []byte
)

func file_carman_proto_rawDescGZIP() []byte {
	file_carman_proto_rawDescOnce.Do(func() {
		file_carman_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_carman_proto_rawDesc), len(file_carman_proto_rawDesc)))
	})
	return file_carman_proto_rawDescData
}

var file_carman_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_carman_proto_goTypes = []any{
	(*Transmission)(nil), // 0: proto.Transmission
	(*Audi)(nil),         // 1: proto.Audi
	(*CarList)(nil),      // 2: proto.CarList
	(*Void)(nil),         // 3: proto.Void
}
var file_carman_proto_depIdxs = []int32{
	0, // 0: proto.Audi.transmission:type_name -> proto.Transmission
	1, // 1: proto.CarList.cars:type_name -> proto.Audi
	1, // 2: proto.CarService.AddAudi:input_type -> proto.Audi
	3, // 3: proto.CarService.GetCars:input_type -> proto.Void
	3, // 4: proto.CarService.AddAudi:output_type -> proto.Void
	2, // 5: proto.CarService.GetCars:output_type -> proto.CarList
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_carman_proto_init() }
func file_carman_proto_init() {
	if File_carman_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_carman_proto_rawDesc), len(file_carman_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_carman_proto_goTypes,
		DependencyIndexes: file_carman_proto_depIdxs,
		MessageInfos:      file_carman_proto_msgTypes,
	}.Build()
	File_carman_proto = out.File
	file_carman_proto_goTypes = nil
	file_carman_proto_depIdxs = nil
}
