// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: CarService.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Car struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vin           string                 `protobuf:"bytes,1,opt,name=vin,proto3" json:"vin,omitempty"`
	Color         string                 `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Car) Reset() {
	*x = Car{}
	mi := &file_CarService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Car) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Car) ProtoMessage() {}

func (x *Car) ProtoReflect() protoreflect.Message {
	mi := &file_CarService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Car.ProtoReflect.Descriptor instead.
func (*Car) Descriptor() ([]byte, []int) {
	return file_CarService_proto_rawDescGZIP(), []int{0}
}

func (x *Car) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

func (x *Car) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type CarList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cars          []*Car                 `protobuf:"bytes,1,rep,name=cars,proto3" json:"cars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CarList) Reset() {
	*x = CarList{}
	mi := &file_CarService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarList) ProtoMessage() {}

func (x *CarList) ProtoReflect() protoreflect.Message {
	mi := &file_CarService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarList.ProtoReflect.Descriptor instead.
func (*CarList) Descriptor() ([]byte, []int) {
	return file_CarService_proto_rawDescGZIP(), []int{1}
}

func (x *CarList) GetCars() []*Car {
	if x != nil {
		return x.Cars
	}
	return nil
}

type Void struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Void) Reset() {
	*x = Void{}
	mi := &file_CarService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Void) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Void) ProtoMessage() {}

func (x *Void) ProtoReflect() protoreflect.Message {
	mi := &file_CarService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Void.ProtoReflect.Descriptor instead.
func (*Void) Descriptor() ([]byte, []int) {
	return file_CarService_proto_rawDescGZIP(), []int{2}
}

var File_CarService_proto protoreflect.FileDescriptor

const file_CarService_proto_rawDesc = "" +
	"\n" +
	"\x10CarService.proto\x12\x05proto\"-\n" +
	"\x03Car\x12\x10\n" +
	"\x03vin\x18\x01 \x01(\tR\x03vin\x12\x14\n" +
	"\x05color\x18\x02 \x01(\tR\x05color\")\n" +
	"\aCarList\x12\x1e\n" +
	"\x04cars\x18\x01 \x03(\v2\n" +
	".proto.CarR\x04cars\"\x06\n" +
	"\x04Void2\x89\x01\n" +
	"\n" +
	"CarService\x12&\n" +
	"\tcreateCar\x12\n" +
	".proto.Car\x1a\v.proto.Void\"\x00\x12(\n" +
	"\agetCars\x12\v.proto.Void\x1a\x0e.proto.CarList\"\x00\x12)\n" +
	"\n" +
	"getAllCars\x12\v.proto.Void\x1a\n" +
	".proto.Car\"\x000\x01B:Z8golang.source-fellows.com/training/carman-grpc/pkg/protob\x06proto3"

var (
	file_CarService_proto_rawDescOnce sync.Once
	file_CarService_proto_rawDescData []byte
)

func file_CarService_proto_rawDescGZIP() []byte {
	file_CarService_proto_rawDescOnce.Do(func() {
		file_CarService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_CarService_proto_rawDesc), len(file_CarService_proto_rawDesc)))
	})
	return file_CarService_proto_rawDescData
}

var file_CarService_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_CarService_proto_goTypes = []any{
	(*Car)(nil),     // 0: proto.Car
	(*CarList)(nil), // 1: proto.CarList
	(*Void)(nil),    // 2: proto.Void
}
var file_CarService_proto_depIdxs = []int32{
	0, // 0: proto.CarList.cars:type_name -> proto.Car
	0, // 1: proto.CarService.createCar:input_type -> proto.Car
	2, // 2: proto.CarService.getCars:input_type -> proto.Void
	2, // 3: proto.CarService.getAllCars:input_type -> proto.Void
	2, // 4: proto.CarService.createCar:output_type -> proto.Void
	1, // 5: proto.CarService.getCars:output_type -> proto.CarList
	0, // 6: proto.CarService.getAllCars:output_type -> proto.Car
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_CarService_proto_init() }
func file_CarService_proto_init() {
	if File_CarService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_CarService_proto_rawDesc), len(file_CarService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_CarService_proto_goTypes,
		DependencyIndexes: file_CarService_proto_depIdxs,
		MessageInfos:      file_CarService_proto_msgTypes,
	}.Build()
	File_CarService_proto = out.File
	file_CarService_proto_goTypes = nil
	file_CarService_proto_depIdxs = nil
}
