// Code generated by MockGen. DO NOT EDIT.
// Source: ../repository.go
//
// Generated by this command:
//
//	mockgen -source=../repository.go -destination=../mocks/repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	model "golang.source-fellows.com/training/carman/v4/internal/model"
)

// MockCarRepository is a mock of CarRepository interface.
type MockCarRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCarRepositoryMockRecorder
	isgomock struct{}
}

// MockCarRepositoryMockRecorder is the mock recorder for MockCarRepository.
type MockCarRepositoryMockRecorder struct {
	mock *MockCarRepository
}

// NewMockCarRepository creates a new mock instance.
func NewMockCarRepository(ctrl *gomock.Controller) *MockCarRepository {
	mock := &MockCarRepository{ctrl: ctrl}
	mock.recorder = &MockCarRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCarRepository) EXPECT() *MockCarRepositoryMockRecorder {
	return m.recorder
}

// AddCar mocks base method.
func (m *MockCarRepository) AddCar(car model.Car) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCar", car)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCar indicates an expected call of AddCar.
func (mr *MockCarRepositoryMockRecorder) AddCar(car any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCar", reflect.TypeOf((*MockCarRepository)(nil).AddCar), car)
}

// GetAllCars mocks base method.
func (m *MockCarRepository) GetAllCars() ([]model.Car, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCars")
	ret0, _ := ret[0].([]model.Car)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllCars indicates an expected call of GetAllCars.
func (mr *MockCarRepositoryMockRecorder) GetAllCars() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCars", reflect.TypeOf((*MockCarRepository)(nil).GetAllCars))
}
